id: 6972e2b4759a4667b7e801ffca7617ee
initial_creation_type: ebook
source_metadata:
  title: ༄༅། །གསང་སྔགས་ཀྱི་ཚུལ་ཁྲིམས་ཀྱི་རྣམ་བཤད་དངོས་གྲུབ་ཀྱི་སྙེ་མ་ཞེས་བྱ་བ་བཞུགས་སོ།།
  subtitle: ''
  authors:
  - རྗེ་བཙུན་ཙོང་ཁ་པ་བློ་བཟང་གྲགས་པ།
  collection: Tsadra Geluk Series
  publisher: Tsadra Publication
  id: TSD-GS-05
  cover: tmpb20dz22a.jpg
  credit: tmp_wnhawfq.jpg
